# Automates deployment of code to each environment
# Triggers when code is pushed to staging or master
# Stores build artifacts in S3 and deploys from those

name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [ master, staging, development ]
    types:
      - completed

  workflow_dispatch:
    inputs:
      deploy_prod:
        description: 'Deploy to Production (true/false)'
        required: true
        default: 'false'

jobs:
  deploy-to-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.STAGING_EC2_SSH_KEY }}
      - name: Make deployment script executable
        run: chmod +x ./scripts/deploy_staging.sh
      - name: Deploy to Staging EC2 Instance
        env:
          CICD_TUTORIAL_ENVIRONMENT: development
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          STAGING_EC2_IP: ${{ secrets.STAGING_EC2_IP }}
        run: ./scripts/deploy_staging.sh
  deploy-to-production:
    if: ${{ github.event.inputs.deploy_prod == 'true' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Make deployment script executable
        run: chmod +x ./scripts/deploy_production.sh
      - name: Deploy to Production EC2 Instance
        env:
          CICD_TUTORIAL_ENVIRONMENT: development
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          PRODUCTION_EC2_IP: ${{ secrets.PRODUCTION_EC2_IP }}
        run: ./scripts/deploy_production.sh