name: Continuous Delivery

on:
  push:
    branches:
      - [ master, staging, development]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Deploy to EC2
      env:
        EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        # Decode the private key and save it to a file
        echo "$EC2_PRIVATE_KEY" | base64 -d > ec2_key.pem
        chmod 600 ec2_key.pem

        # Use SSH to connect to your EC2 instance
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST 'bash -s' < ./scripts/deploy_staging.sh

        # Clean up
        rm ec2_key.pem